---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: examples
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
