---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consul

# Artifact Hub: https://artifacthub.io/packages/helm/hashicorp/consul
# Chart Values: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
helmCharts:
  - name: consul
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    releaseName: consul
    version: 1.4.1
    valuesInline:
      global:
        enabled: false
        logLevel: "info"
        datacenter: homelab
      # client:
      #   enabled: false
      server:
        # enabled: false
        replicas: 1
        bootstrapExpect: 1
        disruptionBudget:
          maxUnavailable: 0
      ui:
        enabled: true
        service:
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "consul"
