---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: consul

helmCharts:
  - name: consul
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    releaseName: consul
    # https://artifacthub.io/packages/helm/hashicorp/consul
    # https://github.com/hashicorp/consul-k8s/releases
    version: 1.4.1
    # https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
    valuesInline:
      global:
        enabled: false
        logLevel: "info"
        datacenter: homelab
      server:
        enabled: true
        replicas: 1
        bootstrapExpect: 1
        disruptionBudget:
          maxUnavailable: 0
      ui:
        enabled: true
        service:
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "consul"
