---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    includeCRDs: true
    valuesInline:
      operatorConfig:
        hostname: "tailscale-operator"
        logging: "info"
    releaseName: tailscale-operator
    # https://github.com/tailscale/tailscale/releases
    version: 1.56.1
    # version: 1.80.0
