---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    includeCRDs: true
    # valuesInline:
    #   oauth:
    #     clientId: ""
    #     clientSecret: ""
    releaseName: tailscale-operator
    version: 1.56.1
