---
- name: Deploy manifests in k8s_manifests to k8s_control_plane.
  hosts: k8s_control_plane
  gather_facts: false

  vars:
    k8s_manage_namespace: false
    k8s_no_log: false
    k8s_manifests_base_dir: k8s_manifests/
    k8s_manifests:
      - dir: monitoring/prometheus
        namespace: monitoring

  tasks:
    - import_role:
        name: geerlingguy.k8s_manifests
      delegate_to: localhost
      run_once: true
