---
# REF: https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  # REF: https://www.home-assistant.io/docs/configuration/basic/#name
  name: "Jason's Home"

  # REF: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # REF: https://www.home-assistant.io/docs/configuration/basic/#time_zone
  time_zone: "America/Los_Angeles"

  # REF: https://www.latlong.net/
  # REF: https://www.home-assistant.io/docs/configuration/basic/#latitude
  # REF: https://www.home-assistant.io/docs/configuration/basic/#longitude
  latitude: !secret latitude
  longitude: !secret longitude

  # REF: https://whatismyelevation.com/map
  # REF: https://www.home-assistant.io/docs/configuration/basic/#elevation
  elevation: !secret elevation

  # REF: https://www.home-assistant.io/docs/configuration/basic/#unit_system
  unit_system: us_customary

  # REF: https://www.home-assistant.io/docs/configuration/basic/#country
  country: "US"

  # REF: https://www.home-assistant.io/docs/configuration/basic/#currency
  currency: "USD"

  # REF: https://www.home-assistant.io/docs/configuration/basic/#external_url
  # REF: https://www.home-assistant.io/docs/configuration/basic/#internal_url
  external_url: "http://jasons-home-assistant.greyhound-little.ts.net:80"
  internal_url: "http://jasons-home-assistant.local:80"


# Loads default set of integrations. Do not remove.
# REF: https://www.home-assistant.io/integrations/default_config/
default_config:


# Load frontend themes from the themes folder.
# REF: https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes


# REF: https://www.home-assistant.io/docs/automation/
# REF: https://www.home-assistant.io/getting-started/automation/
automation: !include automations.yaml


# REF: https://www.home-assistant.io/integrations/script/
script: !include scripts.yaml


# REF: https://www.home-assistant.io/docs/scene/
# REF: https://www.home-assistant.io/integrations/scene/
scene: !include scenes.yaml


# Log Levels: notset, debug, info, warn, warning, error, fatal, critical
# REF: https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    aioesphomeapi.connection: debug
    aiohttp.access: debug
    aiohttp.server: debug
    homeassistant.components.dhcp: debug
    homeassistant.components.discovery: debug
    homeassistant.components.homekit: debug
    homeassistant.components.http.auth: debug
    homeassistant.components.http.view: debug
    homeassistant.components.prometheus: debug
    homeassistant.components.websocket_api.http.connection: debug
    homeassistant.core: debug
    homeassistant.loader: debug
    pyhap.accessory_driver: debug
    pyhap.hap_protocol: debug
    pyhap.hap_server: debug


# REF: https://www.home-assistant.io/integrations/http/
http:
  server_port: 80


# Provide a /api/prometheus endpoint for Prometheus.
# REF: https://www.home-assistant.io/integrations/prometheus/
prometheus:
  namespace: "hass"
  requires_auth: false
