---
#
# EDITOR: http://homeassistant.local:8123/core_configurator/ingress
#
# REF: https://www.home-assistant.io/docs/configuration/

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

aws:
  credentials:
    - name: aws_credentials
      aws_access_key_id: !secret aws_access_key_id
      aws_secret_access_key: !secret aws_secret_access_key
  notify:
    - service: lambda
      region_name: us-east-1
