---
# https://www.macports.org/install.php
- name: Ensure macports is installed.
  hosts: localhost
  become: true

  vars:
    # https://github.com/macports/macports-base/releases/
    # https://github.com/macports/macports-base/releases/download/v2.9.1/MacPorts-2.9.1-14-Sonoma.pkg
    macports_version: 2.9.1
    macports_selfupdate: false
    macports_upgrade_outdated: false

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  roles:
    - role: ansiblebit.macports

  post_tasks:
    - name: Ensure port cli tool is installed.
      command: port version
      changed_when: false
