---
- name: Ensure docker-compose is installed.
  hosts: hass
  become: true

  vars:
    docker_users:
      - pi

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Verify docker is installed.
      command: docker --version
      changed_when: false

    - name: Verify docker-compose is installed.
      command: docker-compose --version
      changed_when: false
