---
- name: Ensure ports are installed.
  hosts: localhost
  become: true

  vars:
    ports:
      - git

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Ensure ports are installed.
      community.general.macports:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        version: "{{ item.version | default(omit) }}"
      loop: "{{ ports }}"
