---
- name: Ensure ports are installed.
  hosts: localhost
  become: true

  vars:
    ports:
      - git

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Ensure ports are installed.
      # https://docs.ansible.com/ansible/latest/collections/community/general/macports_module.html
      community.general.macports:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
        variant: "{{ item.variant | default(omit) }}"
      loop: "{{ ports }}"
