---
- name: Ensure osx-command-line-tools are installed.
  hosts: localhost
  become: true

  vars:
    force_install: true

  roles:
    - elliotweiser.osx-command-line-tools

  post_tasks:
    - name: Verify osx-command-line-tools are installed.
      command: xcode-select --print-path
      changed_when: false
