---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

# Documentation: https://tailscale.com/kb/1236/kubernetes-operator
# Docker Images: https://hub.docker.com/r/tailscale/k8s-operator/tags
# Artifact Hub: N/A
# Chart Values: https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/values.yaml
helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    includeCRDs: true
    valuesInline:
      operatorConfig:
        hostname: "tailscale-operator"
        logging: "info"
    releaseName: tailscale-operator
    # version: 1.62.1
    version: 1.62.1
