---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    includeCRDs: true
    valuesInline:
      operatorConfig:
        hostname: "tailscale-operator"
        logging: "info"
    releaseName: tailscale-operator
    # Tailscale Releases: https://github.com/tailscale/tailscale/releases
    # Helm Chart Releases: https://pkgs.tailscale.com/helmcharts/index.yaml
    # DOCS: https://tailscale.com/kb/1236/kubernetes-operator
    # renovate: image=tailscale/k8s-operator
    appVersion: "v1.62.1"
