---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

# Artifact Hub: N/A
# Chart Values: https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    includeCRDs: true
    valuesInline:
      configMap:
        log:
          level: info
    releaseName: authelia
    version: 0.8.58
