---
- name: Ensure docker-compose is installed.
  hosts: hass
  become: true

  vars:
    docker_users:
      - pi

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Verify docker is installed.
      command: docker --version
      changed_when: false

    - name: Verify docker-compose is installed.
      command: docker-compose --version
      changed_when: false


- name: Deploy hass.
  hosts: hass
  gather_facts: false
  become: true

  handlers:
    - name: restart service
      systemd:
        name: hass
        daemon_reload: yes
        state: restarted

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Ensure compose directory exists.
      file:
        path: /opt/docker/hass/compose
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure config directory exists.
      file:
        path: /opt/docker/hass/volumes/config
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure var-lib-tailscale directory exists.
      file:
        path: /opt/docker/hass/volumes/var-lib-tailscale
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure docker-compose.yml is up to date.
      template:
        src: "{{ playbook_dir }}/templates/docker-compose.yml"
        dest: /opt/docker/hass/compose/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart service

    - name: Ensure service is up to date.
      template:
        src: "{{ playbook_dir }}/templates/hass.service"
        dest: /etc/systemd/system/hass.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart service

    # Restart and/or reload docker-compose service, if required.
    - name: Run handlers.
      meta: flush_handlers

    - name: Pull latest docker image.
      command: docker pull lscr.io/linuxserver/homeassistant:latest

    - name: Ensure service is running as desired.
      service:
        name: hass
        state: started
        enabled: true
      async: 30
      poll: 5
