---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      configmapReload:
        prometheus:
          extraArgs:
            log-level: "all"
      extraScrapeConfigs: |
        - job_name: 'airgradient'
          static_configs:
            - targets:
              - 192.168.1.232
      server:
        service:
          enabled: true
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "prometheus"
        persistentVolume:
          enabled: false
    releaseName: prometheus
    version: 23.4.0
