---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      extraScrapeConfigs: "" # |
        # - job_name: 'esphome-airgradient-exporter'
        #   static_configs:
        #     - targets:
        #       - http://192.168.1.232

        # - job_name: 'prometheus-blackbox-exporter'
        #   metrics_path: /probe
        #   params:
        #     module: [http_2xx]
        #   static_configs:
        #     - targets:
        #       - https://example.com
        #   relabel_configs:
        #     - source_labels: [__address__]
        #       target_label: __param_target
        #     - source_labels: [__param_target]
        #       target_label: instance
        #     - target_label: __address__
        #       replacement: prometheus-blackbox-exporter:9115
      server:
        service:
          enabled: true
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "prometheus"
        persistentVolume:
          enabled: false
        remoteWrite:
          - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-d31d34d9-0d0d-4d03-b661-d54dcbd033d1/api/v1/remote_write
            sigv4:
              region: us-east-1
            queue_config:
              max_samples_per_send: 1000
              max_shards: 200
              capacity: 2500
    releaseName: prometheus
    version: 23.4.0
