---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      server:
        remoteWrite:
          - url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-d31d34d9-0d0d-4d03-b661-d54dcbd033d1/api/v1/remote_write
            sigv4:
              region: us-east-1
            queue_config:
              max_samples_per_send: 1000
              max_shards: 200
              capacity: 2500
        persistentVolume:
          enabled: false
        service:
          enabled: true
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "prometheus"
    releaseName: prometheus
    version: 23.4.0
