---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      alertmanager:
        enabled: false
      kube-state-metrics:
        enabled: false
      prometheus-node-exporter:
        enabled: false
      prometheus-pushgateway:
        enabled: false
      configmapReload:
        prometheus:
          extraArgs:
            log-level: "all"
      extraScrapeConfigs: |
        - job_name: 'airgradient'
          static_configs:
            - targets:
              - 192.168.1.232
      serverFiles:
        ## Alerts configuration
        ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
        alerting_rules.yml:
          groups:
            - name: airgradient.rules
              rules:
                - alert: InstanceDown
                  expr: up{job="airgradient"} == 0
                  for: 5m
                  labels:
                    severity: page
                  annotations:
                    description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
                    summary: 'Instance {{ $labels.instance }} down'

                - alert: HighCO2
                  expr: esphome_sensor_value{id="co2_ppm"} > 200
                  for: 30s
                  labels:
                    severity: page
                  annotations:
                    description: 'DESC: HIGH CO2.'
                    summary: 'SUMM: HIGH CO2.'
      server:
        service:
          enabled: true
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "prometheus"
        persistentVolume:
          enabled: false
    releaseName: prometheus
    version: 23.4.0
