---
# V3
- name: Show the kubeconfig file.
  hosts: control_plane
  gather_facts: false

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong
