---
- name: Set up cluster-wide configuration.
  hosts: cluster
  gather_facts: false
  become: true
  tags:
    - control_plane
    - nodes

  handlers:
    - name: reboot-pi
      ansible.builtin.reboot:

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    # TODO /boot/cmdline.txt is no longer used, use instead /boot/firmware/cmdline.txt.
    # See: https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/c62cf1a12f4e422c855f7e2fcb39e9cadcb5459b
    - name: Ensure cgroups are configured correctly in /boot/firmware/cmdline.txt.
      ansible.builtin.replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
        - "cgroup_memory=1"
        - "cgroup_enable=memory"
      notify: reboot-pi
      tags:
        - boot-cmdline

    - name: Download K3s install script.
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: "~/k3s_install.sh"
        mode: a+x


- name: Configure the control plane.
  hosts: control_plane
  gather_facts: false
  become: true
  tags:
    - control_plane
    - nodes

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Install K3s on control plane (takes a while).
      ansible.builtin.shell: >-
        K3S_DEBUG=true
        K3S_KUBECONFIG_MODE="0644"
        K3S_KUBECONFIG_OUTPUT="/etc/rancher/k3s/k3s.yaml"
        ~/k3s_install.sh > ~/k3s_install_log.txt
      args:
        chdir: "~"
        creates: /var/lib/rancher/k3s/server/node-token

    - name: Get node token.
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      changed_when: false
      register: node_token_output

    - name: Set node_token fact.
      ansible.builtin.set_fact:
        node_token: "{{ node_token_output.stdout_lines[0] }}"


- name: Configure the worker nodes.
  hosts: nodes
  gather_facts: false
  become: true
  tags:
    - nodes

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Install K3s on nodes (takes a while).
      ansible.builtin.shell: >-
        K3S_DEBUG=true
        K3S_TOKEN="{{ hostvars[groups['control_plane'][0]]['node_token'] }}"
        K3S_URL="https://{{ groups['control_plane'][0] }}:6443"
        ~/k3s_install.sh > ~/k3s_install_log.txt
      args:
        chdir: "~"
        creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
