---
- name: Ensure docker-compose is installed.
  hosts: home-assistant
  become: true

  vars:
    docker_users:
      - pi

  roles:
    - geerlingguy.docker

  post_tasks:
    - name: Verify docker is installed.
      command: docker --version
      changed_when: false

    - name: Verify docker-compose is installed.
      command: docker-compose --version
      changed_when: false


- name: Deploy home-assistant.
  hosts: home-assistant
  gather_facts: false
  become: true

  handlers:
    - name: restart service
      systemd:
        name: home-assistant
        daemon_reload: yes
        state: restarted

  tasks:
    - name: Ensure compose directory exists.
      file:
        path: /opt/docker/home-assistant/compose
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure config directory exists.
      file:
        path: /opt/docker/home-assistant/volumes/config
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure docker-compose.yml is up to date.
      template:
        src: "{{ playbook_dir }}/templates/docker-compose.yml"
        dest: /opt/docker/home-assistant/compose/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart service

    - name: Ensure service is up to date.
      template:
        src: "{{ playbook_dir }}/templates/home-assistant.service"
        dest: /etc/systemd/system/home-assistant.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart service

    # Restart and/or reload docker-compose service, if required.
    - name: Run handlers.
      meta: flush_handlers

    - name: Pull docker image.
      command: docker pull lscr.io/linuxserver/homeassistant:2023.10.1

    - name: Ensure service is running as desired.
      service:
        name: home-assistant
        state: started
        enabled: true
      async: 30
      poll: 5
