---
# V3
- name: Print and save the kubeconfig file from the remote host to localhost.
  hosts: control_plane
  gather_facts: false

  pre_tasks:
    - name: Ping to validate the initial connection.
      ansible.builtin.ping:
        data: pong

  tasks:
    - name: Set facts.
      set_fact:
        k3s_kubeconfig_remote_path: /etc/rancher/k3s/k3s.yaml
        k3s_kubeconfig_localhost_path: "/tmp/k3s-{{ inventory_hostname }}-kubeconfig"

    - name: Get kubeconfig and save as k3s_kubeconfig.
      command: cat "{{ k3s_kubeconfig_remote_path }}"
      changed_when: false
      register: k3s_kubeconfig

    - name: Parse k3s_kubeconfig into k3s_kubeconfig_yaml.
      set_fact:
        k3s_kubeconfig_yaml: "{{ k3s_kubeconfig.stdout | from_yaml }}"

    - name: Print k3s_kubeconfig_yaml (for node {{ inventory_hostname }}).
      debug: var=k3s_kubeconfig_yaml

    - name: Save /etc/rancher/k3s/k3s.yaml from the remote host to {{ k3s_kubeconfig_localhost_path }} on the localhost (to use, copy to ~/.kube/config).
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ k3s_kubeconfig_localhost_path }}"
        flat: true
