---
# https://community.home-assistant.io/t/improving-docker-security-non-root-configuration/399971
# https://community.home-assistant.io/t/zigbee-config-docker-access-to-usb-stick/226567

version: '3'

services:
  hass:
    image: lscr.io/linuxserver/homeassistant:2023.10.1
    container_name: hass
    # network_mode: host
    environment:
      - TZ=America/Los_Angeles
      # TODO DOCS: https://github.com/tailscale-dev/docker-mod
      # - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
    volumes:
      - type: bind
        source: "${CONFIG_DIR:-./volumes/config}"
        target: /config
      # - type: bind
      #   source: /run/dbus
      #   target: /run/dbus
      #   read_only: true
      # - type: bind
      #   source: /dev/serial/by-id
      #   target: /dev/serial/by-id
      #   read_only: true
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    ports:
      - 8123:8123
