---
# https://community.home-assistant.io/t/improving-docker-security-non-root-configuration/399971

version: '3'

services:
  hass:
    image: lscr.io/linuxserver/homeassistant:2023.12.3
    container_name: hass
    # Discover devices on the host network.
    # See: https://github.com/linuxserver/docker-homeassistant#host-vs-bridge
    network_mode: host
    environment:
      - TZ=America/Los_Angeles
      # TODO
      # See: https://tailscale.dev/blog/docker-mod-tailscale
      # See: https://github.com/tailscale-dev/docker-mod
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=${TAILSCALE_SERVE_MODE:-https}
      - TAILSCALE_SERVE_PORT=${TAILSCALE_SERVE_PORT:-8123}
      - TAILSCALE_USE_SSH=${TAILSCALE_USE_SSH:-1}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME:-hass}
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY:-0}
    # Access the bluetooth device.
    # See: https://github.com/linuxserver/docker-homeassistant#accessing-bluetooth-device
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      # Access the bluetooth device.
      # See: https://github.com/linuxserver/docker-homeassistant#accessing-bluetooth-device
      - /var/run/dbus:/var/run/dbus:ro
      # Access the usb devices.
      # See: https://community.home-assistant.io/t/zigbee-config-docker-access-to-usb-stick/226567
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      # Access the usb devices.
      # See: https://community.home-assistant.io/t/zigbee-config-docker-access-to-usb-stick/226567
      - /dev/serial/by-id:/dev/serial/by-id
      - "${CONFIG_VOLUME_DIR:-./volumes/config}:/config"
      - "${TAILSCALE_VOLUME_DIR:-./volumes/tailscale}:/var/lib/tailscale"
    # ports:
    #   - 8123:8123
