---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

# Artifact Hub: https://artifacthub.io/packages/helm/grafana/grafana-agent
# Chart Values: https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/values.yaml
helmCharts:
  - name: grafana-agent
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    # valuesInline:
    #   service:
    #     enabled: true
    #     annotations:
    #       # https://tailscale.com/kb/1236/kubernetes-operator/
    #       tailscale.com/expose: "true"
    #       tailscale.com/hostname: "grafana"
    releaseName: grafana-agent
    version: 0.30.0
