---
kind: Service
apiVersion: v1
metadata:
  name: http-https-echo
  annotations:
    # https://tailscale.com/kb/1236/kubernetes-operator/
    tailscale.com/expose: "true"
    tailscale.com/hostname: "http-https-echo"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
