---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    includeCRDs: true
    valuesInline:
      configMap:
        log:
          level: info
    releaseName: authelia
    # https://charts.authelia.com/
    # https://github.com/authelia/chartrepo/tree/master/charts/authelia
    version: 0.8.58
