---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

# See: https://artifacthub.io/packages/helm/grafana/grafana
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      adminUser: admin
      adminPassword: password
      service:
        enabled: true
        annotations:
          # https://tailscale.com/kb/1236/kubernetes-operator/
          tailscale.com/expose: "true"
          tailscale.com/hostname: "grafana"
    releaseName: grafana
    version: 7.0.19
