---
# https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core
- name: Install homeassistant.
  hosts: ha
  gather_facts: false
  become: true

  tasks:
    - name: Ensure dependencies are installed.
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - tzdata
        state: present

    - name: Add ppa:deadsnakes/ppa repo.
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Update apt cache.
      apt:
        update_cache: true
      changed_when: false

    - name: Ensure dependencies are installed.
      package:
        name:
          - python3.11
        state: present

    - name: Ensure homeassistant user exists.
      user:
        name: homeassistant
        shell: /bin/bash
        groups: dialout,gpio,i2c
        createhome: true
        home: /home/homeassistant
        state: present

    - name: Ensure /srv/homeassistant directory exists.
      file:
        path: /srv/homeassistant
        owner: homeassistant
        state: directory
        mode: '0755'

    - name: Initialize the virtualenv environment.
      command:
        cmd: python3 -m venv /srv/homeassistant
        creates: /srv/homeassistant/bin/activate

    - name: Ensure pip is up-to-date (within virtualenv).
      pip:
        name:
          - pip
        extra_args: --upgrade
        virtualenv: /srv/homeassistant
        state: present

    - name: Ensure pip packages are installed (within virtualenv).
      pip:
        name:
          - homeassistant==2023.10.0
        extra_args: --upgrade
        virtualenv: /srv/homeassistant
        state: present

    - name: Ensure homeassistant service is up-to-date.
      template:
        src: homeassistant.service.j2
        dest: /etc/systemd/system/homeassistant.service
        owner: root
        group: root
        mode: '0644'

    # - name: Ensure homeassistant service is running as desired.
    #   service:
    #     name: homeassistant
    #     state: started
    #     enabled: true
