---
- name: Install homeassistant.
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Ensure Pip is installed.
      package:
        name:
          - python3-pip
        state: present

    - name: Ensure homeassistant is installed.
      pip:
        name:
          - homeassistant==2023.9.3
        state: present
