---
- name: Install homeassistant.
  hosts: ha
  gather_facts: false
  become: true

    - name: Ensure docker-compose file is up-to-date.
      template:
        src: docker-compose.yml.j2
        dest: /tmp/docker-compose.yml
        owner: root
        group: root
        mode: '0644'
