---
- name: Install homeassistant.
  hosts: ha
  gather_facts: false
  become: true

  tasks:
    - name: Ensure homeassistant dependencies are installed.
      package:
        name:
          - python3-pip
          - python3-venv
        state: present

    - name: Ensure homeassistant is installed.
      pip:
        name:
          - homeassistant
        state: present

    - name: Ensure homeassistant user exists.
      user:
        name: homeassistant
        shell: /bin/bash
        groups: "dialout,gpio,i2c"
        createhome: true
        home: /home/homeassistant
        state: present

    - name: Ensure homeassistant service exists.
      template:
        src: homeassistant.service.j2
        dest: "/etc/systemd/system/homeassistant.service"
        owner: root
        group: root
        mode: 0644

    - name: Ensure homeassistant service is running as desired.
      service:
        name: homeassistant
        state: started
        enabled: true
