---
# - name: Upgrade everything on homeassistant machines.
#   hosts: ha
#   gather_facts: false
#   become: true

#   tasks:
#     - name: Upgrade all software.
#       apt:
#         update_cache: true
#         upgrade: dist

#     - name: Check if a reboot is required.
#       stat:
#         path: /var/run/reboot-required
#         get_md5: no
#       register: reboot_required_file

#     - name: Reboot the machine (if required).
#       reboot:
#         reboot_timeout: 300
#       when: reboot_required_file.stat.exists == true

#     - name: Remove dependencies that are no longer required.
#       apt:
#         autoremove: yes


- name: Install homeassistant.
  hosts: ha
  gather_facts: false
  become: true

  tasks:
    - name: Ensure homeassistant dependencies are installed.
      package:
        name:
          - python3-pip
          - python3-venv
        state: present

    - name: Ensure homeassistant is installed.
      pip:
        name:
          - homeassistant
        state: present

    - name: Ensure homeassistant user exists.
      user:
        name: homeassistant
        shell: /bin/bash
        groups: dialout,gpio,i2c
        createhome: true
        home: /home/homeassistant
        state: present

    - name: Ensure /srv/homeassistant directory exists.
      file:
        path: /srv/homeassistant
        owner: homeassistant
        state: directory
        mode: '0755'

    - name: Ensure homeassistant service exists.
      template:
        src: homeassistant.service.j2
        dest: /etc/systemd/system/homeassistant.service
        owner: root
        group: root
        mode: '0644'

    # - name: Ensure homeassistant service is running as desired.
    #   service:
    #     name: homeassistant
    #     state: started
    #     enabled: true
