---
- name: Install homeassistant.
  hosts: ha
  gather_facts: false
  become: true

  tasks:
    - name: Ensure Pip is installed.
      package:
        name:
          - python3-pip
        state: present

    - name: Ensure homeassistant is installed.
      pip:
        name:
          - homeassistant
        state: present

    - name: Ensure homeassistant systemd service exists.
      template:
        src: homeassistant.service.j2
        dest: "/etc/systemd/system/homeassistant.service"
        owner: root
        group: root
        mode: 0644
