---
- name: Configure hostname for pi_cluster.
  hosts: pi_cluster
  gather_facts: false
  become: true

  vars:
    raspberry_pi_hostname: "{{ inventory_hostname }}"

  tasks:
    - name: Assert that raspberry_pi_hostname is not empty.
      assert:
        that:
          - raspberry_pi_hostname | length > 0
        quiet: true

    - name: Set the hostname.
      hostname:
        name: "{{ raspberry_pi_hostname }}"
      register: hostname

    - name: Reboot machine.
      reboot:
        reboot_timeout: 300
      when:
        - hostname is changed


- name: Configure tailscale for pi_cluster.
  hosts: pi_cluster
  become: true

  vars:
    tailscale_up_node: true
    tailscale_up_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY', default=undef()) }}"
    tailscale_up_extra_args: "--accept-routes"
    tailscale_up_no_log: false

  roles:
    - jason_riddle.tailscale
