# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# namespace: argocd

# resources:
#   - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    # valuesInline:
    #   service:
    #     enabled: true
    releaseName: argo-cd
    version: 5.46.7
