---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
          timeout.reconciliation: 60s
          timeout.hard.reconciliation: 60s
      server:
        service:
          annotations:
            # https://tailscale.com/kb/1236/kubernetes-operator/
            tailscale.com/expose: "true"
            tailscale.com/hostname: "argocd"
    releaseName: argo-cd
    version: 5.46.7
