---
# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  devicename: "jasons-airgradient-diy-pro"
  upper_devicename: "Jason's AirGradient DIY Pro"


# https://esphome.io/components/esphome.html#esphome-core-configuration
esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"
  platform: ESP8266
  board: d1_mini

  # https://esphome.io/components/esphome.html#on-boot
  on_boot:
    priority: 800
    then:
      - lambda: >-
          ESP_LOGD("main", "ON BOOT!");

  # https://esphome.io/components/esphome.html#on-shutdown
  on_shutdown:
    priority: 600
    then:
      - lambda: >-
          ESP_LOGD("main", "ON SHUTDOWN!");


# https://esphome.io/components/logger
logger:
  level: DEBUG
  logs:
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    logger: INFO
    mqtt.client: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    mqtt: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch.gpio: INFO
    switch: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO
