---
# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:
  devicename: "jasons-airgradient-diy-pro"
  upper_devicename: "Jason's AirGradient DIY Pro"


# https://esphome.io/components/esphome.html#esphome-core-configuration
esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"
  platform: ESP8266
  board: d1_mini

  # https://esphome.io/components/esphome.html#on-boot
  on_boot:
    priority: 800
    then:
      - lambda: >-
          ESP_LOGD("main", "ON BOOT!");

  # https://esphome.io/components/esphome.html#on-shutdown
  on_shutdown:
    priority: 600
    then:
      - lambda: >-
          ESP_LOGD("main", "ON SHUTDOWN!");


# https://esphome.io/components/logger
logger:
  level: DEBUG
  logs:
    adc: INFO
    captive_portal: INFO
    deep_sleep: INFO
    htu21d: INFO
    i2c: INFO
    logger: INFO
    mqtt.client: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    mqtt: INFO
    ota: INFO
    restart: INFO
    sensor: INFO
    switch.gpio: INFO
    switch: INFO
    uptime.sensor: INFO
    web_server: INFO
    wifi_signal.sensor: INFO


# Enable Home Assistant API
# https://esphome.io/components/api
api:
  password: ""


# https://esphome.io/components/ota
ota:
  safe_mode: true
  password: ""


# https://esphome.io/components/wifi
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  reboot_timeout: 15min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # Defaults to device name with no password
  ap: {}
# https://esphome.io/components/captive_portal
captive_portal:


# Provide a /metrics endpoint for Prometheus
# https://esphome.io/components/prometheus
prometheus:
# Please note that enabling this component will take up a lot of memory and may decrease stability, especially on ESP8266.
# https://esphome.io/components/web_server
web_server:
  port: 80
  version: 1


switch:
  # https://esphome.io/components/switch/safe_mode
  # Create a switch for safe_mode in order to flash the device
  # Solution from this thread:
  # https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352/1
  - platform: safe_mode
    name: "Flash Mode (Safe Mode) ON/OFF Switch"
    icon: "mdi:cellphone-arrow-down"

  # https://forum.airgradient.com/t/extending-the-life-span-of-the-pms5003-sensor/114/10
  # Source: https://github.com/airgradienthq/arduino/blob/master/AirGradient.cpp#L123
  - platform: template
    name: "PMS5003 (PM Sensor) ON/OFF Switch"
    id: pms_switch
    optimistic: true
    turn_on_action:
      - uart.write:
          id: pms5003_uart
          data: [0x42, 0x4D, 0xE4, 0x00, 0x01, 0x01, 0x74]
    turn_off_action:
      - uart.write:
          id: pms5003_uart
          data: [0x42, 0x4D, 0xE4, 0x00, 0x00, 0x01, 0x73]


# Create a button to restart the device
button:
  - platform: restart
    name: "Click Button to Restart AirGradient Device (->)"
    id: restart_button
    icon: "mdi:cellphone-arrow-down"


# Configuration for AirGradient DIY v2 device
# https://www.esphome-devices.com/devices/AirGradient-DIY/
# https://github.com/JacobMillward/airgradient_diy_pro_esphome/blob/main/airgradient_diy_pro.yaml

# https://esphome.io/components/uart
uart:
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: senseair_s8_uart

  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: pms5003_uart


# https://esphome.io/components/i2c
i2c:
  sda: D2
  scl: D1
  frequency: 400kHz  # Proposed fix for "Component took a long time for an operation" messages https://github.com/esphome/issues/issues/4717
