.DEFAULT_GOAL := esphome

esphome:
	devenv shell -- esphome run airgradient.yml --device http://192.168.1.232

esphome-usb:
	devenv shell -- esphome run airgradient.yml --device /dev/cu.usbserial-2130
