---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-secrets-operator

helmCharts:
  - name: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    releaseName: vault-secrets-operator
    # https://artifacthub.io/packages/helm/hashicorp/vault-secrets-operator
    # https://github.com/hashicorp/vault-secrets-operator/releases
    version: 0.5.2
    # https://github.com/hashicorp/vault-secrets-operator/blob/main/chart/values.yaml
    valuesInline:
      controller:
        manager:
          clientCache:
            persistenceModel: "direct-encrypted"
            storageEncryption:
              enabled: true
              mount: demo-auth-mount
              keyName: vso-client-cache
              transitMount: demo-transit
              kubernetes:
                role: "auth-role-operator"
                serviceAccount: "demo-operator"
      defaultVaultConnection:
        enabled: true
        address: "http://vault.vault.svc.cluster.local:8200"
        skipTLSVerify: true
      defaultAuthMethod:
        enabled: false
      telemetry:
        serviceMonitor:
          enabled: false
