---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespaces
  - ./apps/authelia/authelia
  # - ./apps/tailscale/tailscale-operator-oauth
  # - ./apps/tailscale/tailscale-operator
