---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    valuesInline:
      injector:
        enabled: false
      server:
        agent:
          enabled: false
        auditStorage:
          enabled: false
        dataStorage:
          enabled: false
        dev:
          enabled: true
      ui:
        enabled: true
        serviceType: "ClusterIP"
        externalPort: 80
        annotations:
          # https://tailscale.com/kb/1236/kubernetes-operator/
          tailscale.com/expose: "true"
          tailscale.com/hostname: "vault"
    releaseName: vault
    # https://github.com/hashicorp/vault-helm/releases
    version: 0.27.0
