---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    releaseName: vault
    # https://artifacthub.io/packages/helm/hashicorp/vault
    # https://github.com/hashicorp/vault-helm/releases
    version: 0.27.0
    valuesInline:
      global:
        enabled: false
      server:
        dev:
          enabled: true
      ui:
        enabled: true
        serviceType: "ClusterIP"
        externalPort: 80
        annotations:
          # https://tailscale.com/kb/1236/kubernetes-operator/
          tailscale.com/expose: "true"
          tailscale.com/hostname: "vault"
