---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: operator-oauth
    envs:
      - .env
