---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

generatorOptions:
  disableNameSuffixHash: true

# https://tailscale.com/kb/1236/kubernetes-operator#prerequisites
# https://login.tailscale.com/admin/settings/oauth
# Permissions: 'Devices' write scope with tag 'tag:k8s-operator'
secretGenerator:
  - name: operator-oauth
    envs:
      - .env
