---
kind: Service
apiVersion: v1
metadata:
  name: whoami
  annotations:
    # https://tailscale.com/kb/1236/kubernetes-operator/
    tailscale.com/expose: "true"
    tailscale.com/hostname: "whoami"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
