---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    # Run at 3pm on Friday.
    # REF: https://crontab.guru/#0_3_*_*_5
    - cron: "0 3 * * 5"

env:
  TAILSCALE_AUTHKEY: "${{ secrets.TAILSCALE_AUTHKEY }}"

jobs:

  integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11 # Bullseye

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible

      - name: Set HOSTNAME.
        run: echo "HOSTNAME=$(cat /etc/hostname)" >> $GITHUB_ENV

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory.yml ./inventory.yml
          ansible-galaxy install -r requirements.yml

      ## Drupal

      ### Drupal - Check.

      # - name: Check drupal/tasks/setup.yml syntax.
      #   run: ansible-playbook drupal/tasks/setup.yml --syntax-check

      # - name: Check drupal/tasks/upgrade.yml syntax.
      #   run: ansible-playbook drupal/tasks/upgrade.yml --syntax-check

      - name: Check drupal/main.yml syntax.
        run: ansible-playbook drupal/main.yml --syntax-check

      ### Drupal - Run.

      # - name: Run drupal/tasks/setup.yml.
      #   run: ansible-playbook drupal/tasks/setup.yml --skip-tags "hostname"

      # - name: Run drupal/tasks/upgrade.yml.
      #   run: ansible-playbook drupal/tasks/upgrade.yml --skip-tags "reboot"

      # - name: Run drupal/tasks/main.yml.
      #   run: ansible-playbook drupal/tasks/main.yml

