# fly.toml app configuration file generated for jasons-fly-golink on 2023-05-01T20:52:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jasons-fly-golink'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'ghcr.io/tailscale/golink:main'

[deploy]
  strategy = 'immediate'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'golink_data_machines'
  destination = '/home/nonroot'
