.DEFAULT_GOAL := deploy

deploy:
	devenv shell -- flyctl deploy --ha=false

# vol-create:
# 	flyctl volumes create golink_data_machines --region=lax --size=1

# vol-list:
# 	flyctl volumes list

# vol-delete:
# 	flyctl volumes destroy <vol_id>
