---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: grafana-agent
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    # valuesInline:
    #   service:
    #     enabled: true
    #     annotations:
    #       # https://tailscale.com/kb/1236/kubernetes-operator/
    #       tailscale.com/expose: "true"
    #       tailscale.com/hostname: "grafana"
    releaseName: grafana-agent
    version: 0.30.0
