---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: alertmanager
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      persistence:
        enabled: false
      service:
        annotations:
          # https://tailscale.com/kb/1236/kubernetes-operator/
          tailscale.com/expose: "true"
          tailscale.com/hostname: "alertmanager"
        port: 80
    releaseName: alertmanager
    version: 1.7.0
