---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: alertmanager
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    valuesInline:
      configmapReload:
        enabled: true
      persistence:
        enabled: false
      service:
        annotations:
          # https://tailscale.com/kb/1236/kubernetes-operator/
          tailscale.com/expose: "true"
          tailscale.com/hostname: "alertmanager"
        port: 80
      config:
        enabled: true
        global:
          # Also possible to place this URL in a file.
          # Ex: `slack_api_url_file: '/etc/alertmanager/slack_url'`
          slack_api_url: "<slack_webhook_url>"
        route:
          receiver: slack-receiver
        receivers:
          - name: slack-receiver
            slack_configs:
              - channel: "#alerts"
                text: "alert"
    releaseName: alertmanager
    version: 1.7.0
